### ISSUE TITLE
picker_row with search + done button

### ISSUE THREAD

**Issue by michelson** [clayallsopp/formotion#187]
Hi @clayallsopp ,

I´ve made an example for a picker row with a search bar to search records in the list.
it´s already working in a current project. btw , It could be improved for sure.
I don't know if make sense to add it as an accessory type like `input_accessory: :search` in formotion core, but at least it could be added as an example for the wiki.

edited: the code example is in https://gist.github.com/michelson/8175905

Best

**Comment by dam13n** [comment]
@michelson thanks for this. helped me add in the "done" on my picker views. seemed like the input accessory thing was for that, but it hasn't worked for me.
