### ISSUE TITLE
Specific dates cannot be selected

### ISSUE THREAD

**Issue by Averethel** [clayallsopp/formotion#242]
Hello @clayallsopp,

We have a problem with date select in our application.
We have a user profile that includes birth date and for some years specific days are impossible to select for example:
  - 1.01 for 2012, 2011, 2010, 2006, 2005, 2000, 1999 - year jumps one year back
  - 31.12 for 2014, 2013, 2012, 2008, 2007, 2003, 2002, 2001 - year jums one year forward
  - 2.01.2000 - year jumps back
  - 3.01.2010 - year jumps back
There are probably more...

Do you have any idea what might be the reason?

![datepicker bug](https://cloud.githubusercontent.com/assets/144707/6960824/4d510850-d926-11e4-989d-2d130e829cd7.png)

**Comment by clayallsopp** [comment]
Hm that's odd, I have no idea off the top of my head. You'll have to dive into the date_row class and do some debugging

**Comment by Averethel** [comment]
It turned out the issue was with a date format string we used.
In case anyone has similar problem check this out: http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns
